### ISSUE TITLE
getDownloadURL api is not working 

### ISSUE THREAD

**Issue by sureshthiyam1337** [maiquocthinh/Terabox-DL#1]
Hi there Pham !
It seems that getDownloadURL api isn't working. So , unable to download videos. Please fix it .

Thanks

**Comment by maiquocthinh** [comment]
Hi there.

This project is not completed yet. API won't work due to expired cookie, jstoken and dp-logid. 

I'll fix it soon in a few days (actually I'm busy). 
So now either you wait for me or you clone the project and replace the expired cookie, jstoken, dp-logid. 

Thanks for your issu.

**Comment by maiquocthinh** [comment]
> Hi there Pham !
> It seems that getDownloadURL api isn't working. So , unable to download videos. Please fix it .
> 
> Thanks 

Hi there.

This project is not completed yet. API won't work due to expired cookie, jstoken and dp-logid. 

I'll fix it soon in a few days (actually I'm busy). 
So now either you wait for me or you clone the project and replace the expired cookie, jstoken, dp-logid. 

Thanks for your issu.

**Comment by sureshthiyam1337** [comment]
I'm waiting for you to fix brother.
Thanks I hope it's fixed soon.
The video info is getting properly, the problem is in download.

**Comment by chirag127** [comment]
> replace the expired cookie, jstoken, dp-logid.

Where to get it.

**Comment by sureshthiyam1337** [comment]
It seems the problem is not for for putting cookies, 
They have another layer for verification "verify_v2", we need to implement this.

**Comment by khainee** [comment]
> > Hi there Pham !
> > It seems that getDownloadURL api isn't working. So , unable to download videos. Please fix it .
> > Thanks
> 
> Hi there.
> 
> This project is not completed yet. API won't work due to expired cookie, jstoken and dp-logid.
> 
> I'll fix it soon in a few days (actually I'm busy). So now either you wait for me or you clone the project and replace the expired cookie, jstoken, dp-logid.
> 
> Thanks for your issu.

How to get dp-logid

**Comment by bleedpink** [comment]
> > > Hi there Pham !
> > > It seems that getDownloadURL api isn't working. So , unable to download videos. Please fix it .
> > > Thanks
> > 
> > 
> > Hi there.
> > This project is not completed yet. API won't work due to expired cookie, jstoken and dp-logid.
> > I'll fix it soon in a few days (actually I'm busy). So now either you wait for me or you clone the project and replace the expired cookie, jstoken, dp-logid.
> > Thanks for your issu.
> 
> How to get dp-logid

Were you able to find the Js_token var?

**Comment by maiquocthinh** [comment]
> Were you able to find the Js_token var?

You can get it here
<img width="959" alt="image" src="https://github.com/maiquocthinh/Terabox-DL/assets/95113661/98432182-823f-482a-b066-794afb8dc688">

**Comment by maiquocthinh** [comment]
> I'm waiting for you to fix brother. Thanks I hope it's fixed soon. The video info is getting properly, the problem is in download.

Fixed 😁. But API won't work due to expired cookie, jstoken and dp-logid.
For now it's only manual replacement, I'll let it auto-renew when it expires later

**Comment by sistematod** [comment]
![Sin título](https://github.com/maiquocthinh/Terabox-DL/assets/121248957/47a980e5-f33d-4bef-940c-ce8371dc810f)
