### ISSUE TITLE
Error -9 ?

### ISSUE THREAD

**Issue by bolbolfolfol** [maiquocthinh/Terabox-DL#10]
Thank you for this great service
but it give me the error in this screenshot : 
https://imgur.com/tIrPxGo

the link in the example is
https://terabox.com/s/1UaQWa3vg4b8Y1Yg4vel4WA
pass : 5dgd

**Comment by r0ld3x** [comment]
Api has been updated by Terabox 

check my repo I made it with updated api

**Comment by r0ld3x** [comment]
> Thank you for this great service but it give me the error in this screenshot : https://imgur.com/tIrPxGo
> 
> the link in the example is https://terabox.com/s/1UaQWa3vg4b8Y1Yg4vel4WA pass : 5dgd

Api has been updated by Terabox

check my repo I made it with updated api

**Comment by KnownBlackHat** [comment]
> > Thank you for this great service but it give me the error in this screenshot : https://imgur.com/tIrPxGo
> > the link in the example is https://terabox.com/s/1UaQWa3vg4b8Y1Yg4vel4WA pass : 5dgd
> 
> Api has been updated by Terabox
> 
> check my repo I made it with updated api

is there any official docs from terabox side regarding this api?

**Comment by r0ld3x** [comment]
> > > Thank you for this great service but it give me the error in this screenshot : https://imgur.com/tIrPxGo
> > > the link in the example is https://terabox.com/s/1UaQWa3vg4b8Y1Yg4vel4WA pass : 5dgd
> > 
> > 
> > Api has been updated by Terabox
> > check my repo I made it with updated api
> 
> is there any official docs from terabox side regarding this api?

Nope it's not its just a scrapped api there is no official api by Tera box

**Comment by KnownBlackHat** [comment]
> > > > Thank you for this great service but it give me the error in this screenshot : https://imgur.com/tIrPxGo
> > > > the link in the example is https://terabox.com/s/1UaQWa3vg4b8Y1Yg4vel4WA pass : 5dgd
> > > 
> > > 
> > > Api has been updated by Terabox
> > > check my repo I made it with updated api
> > 
> > 
> > is there any official docs from terabox side regarding this api?
> 
> Nope it's not its just a scrapped api there is no official api by Tera box

any docs for that scrapped api?

**Comment by r0ld3x** [comment]
> > > > > Thank you for this great service but it give me the error in this screenshot : https://imgur.com/tIrPxGo
> > > > > the link in the example is https://terabox.com/s/1UaQWa3vg4b8Y1Yg4vel4WA pass : 5dgd
> > > > 
> > > > 
> > > > Api has been updated by Terabox
> > > > check my repo I made it with updated api
> > > 
> > > 
> > > is there any official docs from terabox side regarding this api?
> > 
> > 
> > Nope it's not its just a scrapped api there is no official api by Tera box
> 
> any docs for that scrapped api?

Open network tab and check for requests you'll find 

You can take reference from my api terabox repo

**Comment by KnownBlackHat** [comment]
which repo?

**Comment by KnownBlackHat** [comment]
> Open network tab and check for requests you'll find

Currently i am working like that only but the api gives some time unexpected results. so just wanna know how could i handle those

**Comment by r0ld3x** [comment]
> > Open network tab and check for requests you'll find
> 
> Currently i am working like that only but the api gives some time unexpected results. so just wanna know how could i handle those

gitHub.com/r0ld3x/terabox-app
Check backend if this project you'll get api
