### ISSUE TITLE
Failed get url download | Errno: 400310

### ISSUE THREAD

**Issue by 1nhale** [maiquocthinh/Terabox-DL#2]
It gives an error pop-up when trying to download any video

Failed get url download | Errno: 400310

**Comment by chirag127** [comment]
Me getting same error

**Comment by chirag127** [comment]
not getting the error now , maiquocthinh you are genius.

**Comment by chirag127** [comment]
by the way, i modified the code and deployed it at https://terabox-dl.whyiswhen.workers.dev/ 

so, as to download multiple url at once. sorry i'm bad at styling. for example . enter 

```
Mere Sai 👇👇
https://teraboxapp.com/s/1TGyh4WUKArEOanNwDzt-Lg

Dil Diyaan Gaaliyan 👇👇
https://teraboxapp.com/s/1p07_Icj9On4hPfVUuW8u6g

Aheliya bai 👇👇
https://teraboxapp.com/s/16eWLI_fcX3sliGHcij6Wdw

Bade Acche Lagte Hai 3👇👇
https://teraboxapp.com/s/1PFSlr0vATihBDSckSzQ75g

Dhruv Tara 👇👇
https://teraboxapp.com/s/12Aafj_SVV0ib4Mar9Jqz9w
```

in the text area

**Comment by sureshthiyam1337** [comment]
> by the way, i modified the code and deployed it at https://terabox-dl.whyiswhen.workers.dev/
> 
> so, as to download multiple url at once. sorry i'm bad at styling. for example . enter
> 
> ```
> Mere Sai 👇👇
> https://teraboxapp.com/s/1TGyh4WUKArEOanNwDzt-Lg
> 
> Dil Diyaan Gaaliyan 👇👇
> https://teraboxapp.com/s/1p07_Icj9On4hPfVUuW8u6g
> 
> Aheliya bai 👇👇
> https://teraboxapp.com/s/16eWLI_fcX3sliGHcij6Wdw
> 
> Bade Acche Lagte Hai 3👇👇
> https://teraboxapp.com/s/1PFSlr0vATihBDSckSzQ75g
> 
> Dhruv Tara 👇👇
> https://teraboxapp.com/s/12Aafj_SVV0ib4Mar9Jqz9w
> ```
> 
> in the text area

Chirag, Where did you fix the issue for download url?

**Comment by kanishk0013** [comment]
Please fix the issue man 🙏🙏

**Comment by sureshthiyam1337** [comment]
> by the way, i modified the code and deployed it at https://terabox-dl.whyiswhen.workers.dev/
> 
> so, as to download multiple url at once. sorry i'm bad at styling. for example . enter
> 
> ```
> Mere Sai 👇👇
> https://teraboxapp.com/s/1TGyh4WUKArEOanNwDzt-Lg
> 
> Dil Diyaan Gaaliyan 👇👇
> https://teraboxapp.com/s/1p07_Icj9On4hPfVUuW8u6g
> 
> Aheliya bai 👇👇
> https://teraboxapp.com/s/16eWLI_fcX3sliGHcij6Wdw
> 
> Bade Acche Lagte Hai 3👇👇
> https://teraboxapp.com/s/1PFSlr0vATihBDSckSzQ75g
> 
> Dhruv Tara 👇👇
> https://teraboxapp.com/s/12Aafj_SVV0ib4Mar9Jqz9w
> ```
> 
> in the text area

Chirag , the error has arisen now!!!!!

**Comment by 1nhale** [comment]
well if you could share the source with us, we might help fixing the error @chirag127

**Comment by maiquocthinh** [comment]
> Please fix the issue man 🙏🙏

Fixed 😁

**Comment by maiquocthinh** [comment]
API won't work due to expired cookie, jstoken and dp-logid.
For now it's only manual replacement, I'll let it auto-renew when it expires later

**Comment by bleedpink** [comment]
> 

Can you tell me from where i can get that Js_token i was able to find other var but not this one.
thanks.

**Comment by maiquocthinh** [comment]
> > 
> 
> Can you tell me from where i can get that Js_token i was able to find other var but not this one. thanks.

You can find it this way, here:
[https://github.com/maiquocthinh/Terabox-DL/issues/1#issuecomment-1638444452](url)
