### ISSUE TITLE
Failed get url download |  Errno: 400310

### ISSUE THREAD

**Issue by itzrexmodz** [maiquocthinh/Terabox-DL#3]
I am attempting to download Terabox links using the API, but I encountered an error message: 'Failed get url download | Errno: 400310' Do you have any suggestions or solutions to resolve this issue?

**Comment by maiquocthinh** [comment]
> I am attempting to download Terabox links using the API, but I encountered an error message: 'Failed get url download | Errno: 400310' Do you have any suggestions or solutions to resolve this issue?

Fixed 😁
