### ISSUE TITLE
Haven't fixed yet!!! 

### ISSUE THREAD

**Issue by sureshthiyam1337** [maiquocthinh/Terabox-DL#4]
Brother, it seems the problem isn't due to expired cookies or jstoken and dp-logid. If those things are expired, how can it still works to get the video details, 
Recheck "verify_v2" , they have recently implemented Google recaptcha in the login.
Let you put recaptcha bypassing part in your code, parameters when I captured the download request, I got "verify_v2".

Thanks in advance.

**Comment by maiquocthinh** [comment]
> Brother, it seems the problem isn't due to expired cookies or jstoken and dp-logid. If those things are expired, how can it still works to get the video details, Recheck "verify_v2" , they have recently implemented Google recaptcha in the login. Let you put recaptcha bypassing part in your code, parameters when I captured the download request, I got "verify_v2".
> 
> Thanks in advance.

Hi

The download problem is entirely caused by cookies, jstoken and dp-logid. If you have this information, you can send a request to get the download link

As for getting sharelink information, there's absolutely no need for cookies, jstoken and dp-logid (look at my code and you'll see)

Thanks

**Comment by sureshthiyam1337** [comment]
I tried sending request using postman putting all the required headers, tokens, but in the response I still get "verify_v2" error.
Can you show me screenshot if you can fix the download url using the information that you mentioned?

**Comment by maiquocthinh** [comment]
> I tried sending request using postman putting all the required headers, tokens, but in the response I still get "verify_v2" error. Can you show me screenshot if you can fix the download url using the information that you mentioned?

I don't get an error when I send a request to get the download link:
![image](https://github.com/maiquocthinh/Terabox-DL/assets/95113661/21291d45-c040-41fd-bc59-0be9044a5a2a)

My params:
app_id, web, channel, clienttype, jsToken, dp-logid, shareid, sign, timestamp, product, nozip, fid_list, uk, primaryid
My header: Cookie

**Comment by sureshthiyam1337** [comment]
Can you make a proper installation way of your typescript project on server, after downloading your repo, some files are missing, like .env config files, please list out the mandatory files needed for installation? Also check your telegram message.

**Comment by maiquocthinh** [comment]
> Can you make a proper installation way of your typescript project on server, after downloading your repo, some files are missing, like .env config files, please list out the mandatory files needed for installation? Also check your telegram message.

Follow this:
1. clone project 
2. run command yarn install
3. edit wrangler.toml
4. run command yarn deploy
5. login cloudflare

**Comment by sureshthiyam1337** [comment]
Can I host it on aws ec2 , vercel and shared hosting too?

**Comment by maiquocthinh** [comment]
> Can I host it on aws ec2 , vercel and shared hosting too?

Maybe, i don't know, but this project work nice on cloudflare.
