### ISSUE TITLE
Error to fetch the link

### ISSUE THREAD

**Issue by james00000007** [maiquocthinh/Terabox-DL#6]
Hello @maiquocthinh ,

getting below error.

![Screenshot 2023-07-24 085749](https://github.com/maiquocthinh/Terabox-DL/assets/95303830/9d464840-6b72-4277-911a-b5a7894ce83f)

**Comment by maiquocthinh** [comment]
> Hello @maiquocthinh ,
> 
> getting below error.
> 
> ![Screenshot 2023-07-24 085749](https://user-images.githubusercontent.com/95303830/255647483-9d464840-6b72-4277-911a-b5a7894ce83f.png)

Hello,
This happens when the cookie, jstoken and dp-logid expire.
If you want to use this tool, you should deploy an app of your own.
Thanks
