### ISSUE TITLE
Download url isn't fixed still.

### ISSUE THREAD

**Issue by sureshthiyam1337** [maiquocthinh/Terabox-DL#7]
Hello @maiquocthinh ,
Have you updated your codes?
 cookies, jstoken and dp-logid,have you updated those necessary variables?

Still , if seems it doesn't work still .

**Comment by maiquocthinh** [comment]
> cookies, jstoken and dp-logid

Hi,
I am not updating the code for cookie, jstoken and dp-logid because it will expire. So if you want to use this tool just implement it and replace your cookie, jstoken and dp-logid.
Bye
